(() => {
  const svg = document.getElementById('canvas'), world = document.getElementById('world');
  const nodeLayer = document.getElementById('nodeLayer'), edgeLayer = document.getElementById('edgeLayer'), edgeGlowLayer = document.getElementById('edgeGlowLayer'), tempLayer = document.getElementById('tempLayer'), signalLayer = document.getElementById('signalLayer');
  const state = {nodes:[],edges:[],nextNode:1,nextEdge:1,tool:'add',rule:'OR',zoom:1,panX:0,panY:0,selected:null,connecting:null,temp:null,drag:null,panning:null,simulating:false};
  const $=id=>document.getElementById(id);
  const toast=(t)=>{const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)};
  const ruleHint={OR:'Mindestens ein Eingang muss aktiv sein.',AND:'Alle Eingänge müssen gleichzeitig aktiv sein.'};
  const nodeBy=id=>state.nodes.find(n=>n.id===id);
  const svgPoint=(clientX,clientY)=>{const r=svg.getBoundingClientRect();return {x:(clientX-r.left-state.panX)/state.zoom,y:(clientY-r.top-state.panY)/state.zoom}};
  const applyWorld=()=>world.setAttribute('transform',`translate(${state.panX},${state.panY}) scale(${state.zoom})`);
  function updateStats(){ $('nodeCount').textContent=state.nodes.length; $('edgeCount').textContent=state.edges.length; $('activeCount').textContent=state.nodes.filter(n=>n.active).length; }
  function setTool(t){state.tool=t;document.querySelectorAll('.tool').forEach(b=>b.classList.remove('active'));document.getElementById(t==='add'?'addNodeBtn':t==='connect'?'connectBtn':'deleteBtn').classList.add('active');$('modeLabel').textContent={add:'Knoten platzieren',connect:'Verbindungen erstellen',delete:'Element löschen'}[t];svg.style.cursor=t==='delete'?'not-allowed':t==='connect'?'crosshair':'crosshair'}
  document.querySelectorAll('.tool').forEach(b=>b.addEventListener('click',()=>setTool(b.id==='addNodeBtn'?'add':b.id==='connectBtn'?'connect':'delete')));
  document.querySelectorAll('.rule').forEach(b=>b.addEventListener('click',()=>{state.rule=b.dataset.rule;document.querySelectorAll('.rule').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('ruleHint').textContent=ruleHint[state.rule];propagate()}));

  function createNode(x,y,type='NODE'){const n={id:state.nextNode++,x,y,type,inputOn:false,active:false,partial:false};state.nodes.push(n);drawNode(n);updateStats();return n}
  function nodeType(n){return n.type==='INPUT'?'INPUT':n.type==='OUTPUT'?'OUTPUT':'NODE'}
  function drawNode(n){
    const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('node-group');g.dataset.id=n.id;
    const ring=document.createElementNS('http://www.w3.org/2000/svg','circle');ring.classList.add('node-ring');ring.setAttribute('r',25);
    const body=document.createElementNS('http://www.w3.org/2000/svg','circle');body.classList.add('node-body');body.setAttribute('r',20);
    const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.classList.add('node-label');label.setAttribute('text-anchor','middle');label.setAttribute('y',3);
    const sub=document.createElementNS('http://www.w3.org/2000/svg','text');sub.classList.add('node-sub');sub.setAttribute('text-anchor','middle');sub.setAttribute('y',34);
    g.append(ring,body,label,sub);nodeLayer.appendChild(g);updateNode(n,g);
    g.addEventListener('pointerdown',e=>{e.stopPropagation();if(state.tool==='connect'){startConnect(n,e)}else if(state.tool==='delete'){deleteNode(n.id)}else{state.drag={n,g,offset:svgPoint(e.clientX,e.clientY)};g.classList.add('dragging');selectNode(n.id)}});
    g.addEventListener('dblclick',e=>{e.stopPropagation();if(n.type==='INPUT'){n.inputOn=!n.inputOn;propagate();toast(n.inputOn?'Input aktiviert':'Input deaktiviert')}else{n.type='INPUT';n.inputOn=false;propagate();toast('Knoten ist jetzt ein Input')}});
    g.addEventListener('click',e=>{e.stopPropagation();if(n.type==='INPUT'&&state.tool==='add'){n.inputOn=!n.inputOn;propagate()}});
  }
  function updateNode(n,g){g.setAttribute('transform',`translate(${n.x},${n.y})`);g.classList.toggle('active',n.active);g.classList.toggle('partial',n.partial);g.classList.toggle('input',n.type==='INPUT');const body=g.querySelector('.node-body');const label=g.querySelector('.node-label'),sub=g.querySelector('.node-sub');body.setAttribute('fill',n.active?'#17382f':n.partial?'#122c45':n.type==='INPUT'?'#211b3b':'#111b2a');label.textContent=n.type==='INPUT'?(n.inputOn?'ON':'IN'):n.type==='OUTPUT'?'OUT':`#${n.id}`;sub.textContent=n.type==='INPUT'?'Input':n.type==='OUTPUT'?'Output':state.rule;}
  function selectNode(id){state.selected=id;document.querySelectorAll('.node-group').forEach(g=>g.style.opacity=(g.dataset.id==id?'1':'.82'));showInspector()}
  function showInspector(){const n=nodeBy(state.selected);const ins=$('inspector');if(!n){ins.classList.add('hidden');return}ins.classList.remove('hidden');document.getElementById('inspectorContent').innerHTML=`<div class="inspect-name">Knoten #${n.id}</div><div class="inspect-type">${nodeType(n)}</div><div class="prop"><span>Position</span><b>${Math.round(n.x)}, ${Math.round(n.y)}</b></div><div class="prop"><span>Status</span><b>${n.active?'AKTIV':'AUS'}</b></div><button class="inspect-btn" id="makeInput">${n.type==='INPUT'?'Input entfernen':'Als Input markieren'}</button><button class="inspect-btn" id="makeOutput">${n.type==='OUTPUT'?'Output entfernen':'Als Output markieren'}</button><button class="inspect-btn delete" id="inspectDelete">Knoten löschen</button>`;document.getElementById('makeInput').onclick=()=>{n.type=n.type==='INPUT'?'NODE':'INPUT';if(n.type!=='INPUT')n.inputOn=false;propagate();showInspector()};document.getElementById('makeOutput').onclick=()=>{n.type=n.type==='OUTPUT'?'NODE':'OUTPUT';propagate();showInspector()};document.getElementById('inspectDelete').onclick=()=>deleteNode(n.id)}
  function deleteNode(id){state.edges=state.edges.filter(e=>e.from!==id&&e.to!==id);state.nodes=state.nodes.filter(n=>n.id!==id);if(state.selected===id)state.selected=null;redrawEdges();redrawNodes();propagate();showInspector();toast('Knoten gelöscht')}
  function redrawNodes(){nodeLayer.innerHTML='';state.nodes.forEach(drawNode);updateStats()}
  function addEdge(from,to){if(from===to||state.edges.some(e=>e.from===from&&e.to===to))return false;state.edges.push({id:state.nextEdge++,from,to});redrawEdges();propagate();return true}
  function redrawEdges(){edgeLayer.innerHTML='';edgeGlowLayer.innerHTML='';for(const e of state.edges){const a=nodeBy(e.from),b=nodeBy(e.to);if(!a||!b)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.classList.add('edge');line.dataset.id=e.id;edgeLayer.appendChild(line);const glow=line.cloneNode();glow.classList.remove('edge');glow.classList.add('edge-glow');edgeGlowLayer.appendChild(glow);setLine(line,a,b);setLine(glow,a,b)}refreshEdges()}
  function setLine(el,a,b){el.setAttribute('x1',a.x);el.setAttribute('y1',a.y);el.setAttribute('x2',b.x);el.setAttribute('y2',b.y)}
  function refreshEdges(){[...edgeLayer.children].forEach((el,i)=>{const e=state.edges.find(x=>x.id==el.dataset.id);const a=nodeBy(e.from),b=nodeBy(e.to);setLine(el,a,b);el.classList.toggle('active',a.active)});[...edgeGlowLayer.children].forEach((el,i)=>{const e=state.edges.find(x=>x.id==el.dataset.id);setLine(el,nodeBy(e.from),nodeBy(e.to));el.style.opacity=nodeBy(e.from)?.active?'.14':'0'});updateStats()}
  function startConnect(n,e){state.connecting=n;const p=svgPoint(e.clientX,e.clientY);state.temp=document.createElementNS('http://www.w3.org/2000/svg','line');state.temp.classList.add('temp-line');state.temp.setAttribute('x1',n.x);state.temp.setAttribute('y1',n.y);state.temp.setAttribute('x2',p.x);state.temp.setAttribute('y2',p.y);tempLayer.appendChild(state.temp)}
  function stopConnect(target){if(state.connecting&&target&&target.id!==state.connecting.id){if(addEdge(state.connecting.id,target.id))toast('Verbindung erstellt');else toast('Verbindung existiert bereits')}if(state.temp?.parentNode)state.temp.remove();state.temp=null;state.connecting=null}
  function findNode(p){let hit=null,best=28;for(const n of state.nodes){const d=Math.hypot(p.x-n.x,p.y-n.y);if(d<best){best=d;hit=n}}return hit}
  function findEdge(p){for(const e of state.edges){const a=nodeBy(e.from),b=nodeBy(e.to);const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)continue;let t=((p.x-a.x)*dx+(p.y-a.y)*dy)/l2;t=Math.max(0,Math.min(1,t));const d=Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy));if(d<8)return e}return null}
  function propagate(){for(const n of state.nodes){n.active=false;n.partial=false}const incoming=new Map(state.nodes.map(n=>[n.id,[]]));state.edges.forEach(e=>incoming.get(e.to)?.push(e.from));for(let i=0;i<state.nodes.length+2;i++){let changed=false;for(const n of state.nodes){const ins=incoming.get(n.id)||[];let a=false,p=false;if(n.type==='INPUT')a=n.inputOn;else if(ins.length){const vals=ins.map(id=>!!nodeBy(id)?.active);a=state.rule==='OR'?vals.some(Boolean):vals.every(Boolean);p=state.rule==='AND'&&vals.some(Boolean)&&!a}if(a!==n.active||p!==n.partial){n.active=a;n.partial=p;changed=true}}if(!changed)break}redrawVisuals();if(state.selected)showInspector()}
  function redrawVisuals(){document.querySelectorAll('.node-group').forEach(g=>{const n=nodeBy(+g.dataset.id);if(n)updateNode(n,g)});refreshEdges()}
  function clearAll(){state.nodes=[];state.edges=[];state.nextNode=1;state.nextEdge=1;state.selected=null;nodeLayer.innerHTML='';edgeLayer.innerHTML='';edgeGlowLayer.innerHTML='';signalLayer.innerHTML='';showInspector();updateStats();toast('Arbeitsfläche geleert')}
  function demo(){clearAll();state.panX=0;state.panY=0;state.zoom=1;applyWorld();const a=createNode(140,250,'INPUT'),b=createNode(140,390,'INPUT'),g=createNode(340,320,'NODE'),o=createNode(540,320,'OUTPUT');a.inputOn=true;addEdge(a.id,g.id);addEdge(b.id,g.id);addEdge(g.id,o.id);propagate();toast('Demo-Netzwerk geladen')}
  function animateSignal(){if(state.simulating)return;const activeEdges=state.edges.filter(e=>nodeBy(e.from)?.active);if(!activeEdges.length){toast('Kein aktiver Signalweg');return}state.simulating=true;$('simulateBtn').classList.add('running');$('simulateBtn').innerHTML='<span>●</span> Signal läuft';let i=0;const run=()=>{if(i>=activeEdges.length){state.simulating=false;$('simulateBtn').classList.remove('running');$('simulateBtn').innerHTML='<span>▶</span> Signal testen';return}const e=activeEdges[i++],a=nodeBy(e.from),b=nodeBy(e.to),dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.classList.add('signal');dot.setAttribute('r',4);signalLayer.appendChild(dot);const start=performance.now(),dur=500;function frame(t){const q=Math.min(1,(t-start)/dur);dot.setAttribute('cx',a.x+(b.x-a.x)*q);dot.setAttribute('cy',a.y+(b.y-a.y)*q);if(q<1)requestAnimationFrame(frame);else{dot.remove();run()}}requestAnimationFrame(frame)};run()}
  $('addNodeBtn').onclick=()=>setTool('add');$('connectBtn').onclick=()=>setTool('connect');$('deleteBtn').onclick=()=>setTool('delete');$('clearBtn').onclick=clearAll;$('demoBtn').onclick=demo;$('resetInputsBtn').onclick=()=>{state.nodes.forEach(n=>{if(n.type==='INPUT')n.inputOn=false});propagate()};$('simulateBtn').onclick=animateSignal;
  $('zoomIn').onclick=()=>{state.zoom=Math.min(2.5,state.zoom*1.15);applyWorld();$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'};$('zoomOut').onclick=()=>{state.zoom=Math.max(.35,state.zoom/1.15);applyWorld();$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'};$('zoomReset').onclick=()=>{state.zoom=1;state.panX=state.panY=0;applyWorld();$('zoomLabel').textContent='100%'};
  svg.addEventListener('pointermove',e=>{if(state.drag){const p=svgPoint(e.clientX,e.clientY),n=state.drag.n;n.x=p.x;n.y=p.y;updateNode(n,state.drag.g);redrawEdges()}if(state.temp){const p=svgPoint(e.clientX,e.clientY);state.temp.setAttribute('x2',p.x);state.temp.setAttribute('y2',p.y)}if(state.panning){state.panX=e.clientX-state.panning.x;state.panY=e.clientY-state.panning.y;applyWorld()}});
  window.addEventListener('pointerup',e=>{if(state.drag){state.drag.g.classList.remove('dragging');state.drag=null}if(state.temp){stopConnect(findNode(svgPoint(e.clientX,e.clientY)))}state.panning=null});
  svg.addEventListener('pointerdown',e=>{if(e.button===1||e.code==='Space'||e.shiftKey){state.panning={x:e.clientX-state.panX,y:e.clientY-state.panY};e.preventDefault();return}if(e.target===svg||e.target.id==='gridRect'){const p=svgPoint(e.clientX,e.clientY);if(state.tool==='add'){createNode(p.x,p.y);propagate()}else if(state.tool==='delete'){const edge=findEdge(p);if(edge){state.edges=state.edges.filter(x=>x.id!==edge.id);redrawEdges();propagate();toast('Verbindung gelöscht')}}else{state.selected=null;showInspector()}}});
  svg.addEventListener('wheel',e=>{e.preventDefault();const before=svgPoint(e.clientX,e.clientY),factor=e.deltaY<0?1.1:.9;state.zoom=Math.max(.35,Math.min(2.5,state.zoom*factor));state.panX=e.clientX-svg.getBoundingClientRect().left-before.x*state.zoom;state.panY=e.clientY-svg.getBoundingClientRect().top-before.y*state.zoom;applyWorld();$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'},{passive:false});
  window.addEventListener('keydown',e=>{if(e.code==='Delete'&&state.selected)deleteNode(state.selected);if(e.code==='Escape'){state.connecting=null;if(state.temp)state.temp.remove();state.temp=null}});
  demo();
})();
